myclass cl,cl1;
void setup()
{
size(600,600);

cl=new myclass(100);

cl1=new myclass(400,200,60);
}

void draw()
{
cl.cir();
cl1.cir();

cl.valuechange(cl1,60,160);
cl1.cir();
}

// PASS BY VALUE VS PASS BY REFERNCE, WHAT IT MEANS IS THAT, IF THE PRIMITIVE DATATYPES ARE USED IN THE METHODS, AND THEY ARE CHANGED, IT IS INSTANTIATED BY PASS BY VALUE --> THE ORIGINAL VALUE DOESNOT CHANGES!!
// IF FOR EXAMPLE, cl1.cir() , IT IS CALLED AGAIN AFTER CHANGING THE RADII AND X VALUES, BUT IT IS PASS BY REFERENCE BECUASE THE OBJECT cl1 HERE AFTER HAVE THE CHANGED RADII AND X VALUE!
